function create_occipital(session_dir,subject_name,SUBJECTS_DIR)

% Creates an occipital ROI using freesurfer, based on all occipital labels
% in the aparc.a2009s annotation
%
%   Usage: create_occipital(session_dir,subject_name,SUBJECTS_DIR)
%
%   Written by Andrew S Bock Feb 2015

%% Set defaults
if ~exist('session_dir','var')
    error('No ''session_dir'' defined')
end
if ~exist('subject_name','var')
    error('No ''subject_name'' defined')
end
if ~exist('SUBJECTS_DIR','var')
    SUBJECTS_DIR = getenv('SUBJECTS_DIR');
end
repo_path = which('create_occipital');
repo_path = fileparts(repo_path);
%% Add to log
SaveLogInfo(session_dir,mfilename,session_dir,subject_name,SUBJECTS_DIR)

%% occipital ROI
disp(['session_dir = ' session_dir]);
disp(['subject_name = ' subject_name]);
disp('Creating occipital ROI...');
% create lh.occipital.annot if doesn't exist for fsaverage_sym
cd(fullfile(SUBJECTS_DIR,'fsaverage_sym','label'))
mkdir('occipital_tmp');
cd('./occipital_tmp')
[~,~] = system(['mri_annotation2label --subject fsaverage_sym --hemi lh --outdir ./' ...
    ' --annotation aparc.a2009s']);
[~,~] = system(['mri_mergelabels ' ...
    '-i lh.G_and_S_occipital_inf.label -i lh.G_cuneus.label ' ...
    '-i lh.G_occipital_middle.label -i lh.G_occipital_sup.label ' ...
    '-i lh.G_oc-temp_med-Lingual.label -i lh.G_oc-temp_med-Parahip.label ' ...
    '-i lh.G_cingul-Post-ventral.label -i lh.G_oc-temp_lat-fusifor.label ' ...
    '-i lh.S_calcarine.label -i lh.S_collat_transv_post.label ' ...
    '-i lh.S_oc_middle_and_Lunatus.label -i lh.S_oc_sup_and_transversal.label ' ...
    '-i lh.S_oc-temp_med_and_Lingual.label -i lh.S_parieto_occipital.label ' ...
    '-i lh.Pole_occipital.label ' ...
    '-o ' fullfile(SUBJECTS_DIR,'fsaverage_sym','label','lh.occipital.label')]);
delete('./*')
cd ..; rmdir('./occipital_tmp');
% make annot
if exist(fullfile(SUBJECTS_DIR,'fsaverage_sym','label','lh.occipital.annot'),'file') ...
        || exist(fullfile(SUBJECTS_DIR,'fsaverage_sym','label','rh.occipital.annot'),'file');
    system(['rm ' fullfile(SUBJECTS_DIR,'fsaverage_sym','label','*.occipital.annot')]);
end
[~,~] = system(['mris_label2annot --s fsaverage_sym --h lh --ctab ' ...
    fullfile(repo_path,'occipital.ctab') ' --l ' ...
    fullfile(SUBJECTS_DIR,'fsaverage_sym','label','lh.occipital.label') ...
    ' --a occipital']);
% Project to 'occipital' label to subject surface
% Create annotation file
if exist(fullfile(SUBJECTS_DIR,subject_name,'label','lh.occipital.annot'),'file') ...
        || exist(fullfile(SUBJECTS_DIR,subject_name,'label','rh.occipital.annot'),'file');
    system(['rm ' fullfile(SUBJECTS_DIR,subject_name,'label','*.occipital.annot')]);
end
% lh
[~,~] = system(['mri_label2label --srclabel ' ...
    fullfile(SUBJECTS_DIR,'fsaverage_sym','label','lh.occipital.label') ...
    ' --srcsubject fsaverage_sym --trgsubject ' subject_name ' --trglabel ' ...
    fullfile(SUBJECTS_DIR,subject_name,'label','lh.occipital.label') ...
    ' --regmethod surface --hemi lh']);
[~,~] = system(['mris_label2annot --s ' subject_name ' --h lh --ctab ' ...
    fullfile(repo_path,'occipital.ctab') ' --l ' ...
    fullfile(SUBJECTS_DIR,subject_name,'label','lh.occipital.label') ...
    ' --a occipital']);
% rh
[~,~] = system(['mri_label2label --srclabel ' ...
    fullfile(SUBJECTS_DIR,'fsaverage_sym','label','lh.occipital.label') ...
    ' --srcsubject fsaverage_sym --trgsubject ' subject_name '/xhemi --trglabel ' ...
    fullfile(SUBJECTS_DIR,subject_name,'label','rh.occipital.label') ...
    ' --regmethod surface --hemi lh']);
[~,~] = system(['mris_label2annot --s ' subject_name ' --h rh --ctab ' ...
    fullfile(repo_path,'occipital.ctab') ' --l ' ...
    fullfile(SUBJECTS_DIR,subject_name,'label','rh.occipital.label')...
    ' --a occipital']);
disp('done.');