function segment_gm(session_dir,subject_name)

%% Set default parameters
if ~exist('session_dir','var')
    error('"session_dir" not defined')
end
if ~exist('subject_name','var')
    error('"subject_name" not defined')
end

SUBJECTS_DIR = getenv('SUBJECTS_DIR');

%% Segment GM
disp('Segmenting GM, WM, ventricles, brainstem, and non-brain tissue');
% Brain (will be used as brain mask and to find grey matter)
[~,~] = system(['mri_binarize --i ' fullfile(SUBJECTS_DIR,subject_name,'mri','brain.mgz') ...
    ' --min 1 --o ' fullfile(session_dir,'brain.nii.gz')]);
% White matter
[~,~] = system(['mri_binarize --i ' fullfile(SUBJECTS_DIR,subject_name,'mri','aseg.mgz') ...
    ' --match 2 7 41 46 251 252 253 254 255 --erode 1 --o ' fullfile(session_dir,'aseg.wm.nii.gz')]);
% Left lateral ventricle
[~,~] = system(['mri_binarize --i ' fullfile(SUBJECTS_DIR,subject_name,'mri','aseg.mgz') ...
    ' --match 4 --erode 1 --o ' fullfile(session_dir,'aseg.lh_ventricle.nii.gz')]);
% Right right lateral ventricle
[~,~] = system(['mri_binarize --i ' fullfile(SUBJECTS_DIR,subject_name,'mri','aseg.mgz') ...
    ' --match 43 --erode 1 --o ' fullfile(session_dir,'aseg.rh_ventricle.nii.gz')]);
% Third ventricle
[~,~] = system(['mri_binarize --i ' fullfile(SUBJECTS_DIR,subject_name,'mri','aseg.mgz') ...
    ' --match 14 --erode 1 --o ' fullfile(session_dir,'aseg.third_ventricle.nii.gz')]);
% Fourth ventricle
[~,~] = system(['mri_binarize --i ' fullfile(SUBJECTS_DIR,subject_name,'mri','aseg.mgz') ...
    ' --match 15 --erode 1 --o ' fullfile(session_dir,'aseg.fourth_ventricle.nii.gz')]);
% brainstem (WM)
% note: need to erode brainstem more, as it includes some GM structures (e.g. SC)
[~,~] = system(['mri_binarize --i ' fullfile(SUBJECTS_DIR,subject_name,'mri','aseg.mgz') ...
    ' --match 16 --erode 5 --o ' fullfile(session_dir,'aseg.brainstem.nii.gz')]);
% Unknown (non-brain voxels)
[~,~] = system(['mri_binarize --i ' fullfile(SUBJECTS_DIR,subject_name,'mri','aseg.mgz') ...
    ' --match 0 --erode 1 --o ' fullfile(session_dir,'aseg.unknown.nii.gz')]);
[~,~] = system(['fslmaths ' fullfile(session_dir,'aseg.unknown.nii.gz') ' -mul '...
    fullfile(session_dir,'brain.nii.gz') ' ' fullfile(session_dir,'aseg.unknown.nii.gz')]);
% Segment GM by removing eroded non-GM structures from brain.nii.gz
[~,~] = system(['fslmaths ' fullfile(session_dir,'brain.nii.gz') ' -sub ' ...
    fullfile(session_dir,'aseg.wm.nii.gz') ' -sub ' ...
    fullfile(session_dir,'aseg.lh_ventricle.nii.gz') ' -sub ' ...
    fullfile(session_dir,'aseg.rh_ventricle.nii.gz') ' -sub ' ...
    fullfile(session_dir,'aseg.third_ventricle.nii.gz') ' -sub ' ...
    fullfile(session_dir,'aseg.fourth_ventricle.nii.gz') ' -sub ' ...
    fullfile(session_dir,'aseg.brainstem.nii.gz') ' -sub ' ...
    fullfile(session_dir,'aseg.unknown.nii.gz') ' -bin ' ...
    fullfile(session_dir,'aseg.gm.nii.gz')]);